### ISSUE TITLE
app.go doesn't route PATCH verbs properly

### ISSUE THREAD

**Issue by bruferrari** [novatrixtech/mercurius#15]
Just realized that Mercurius doesn't route **PATCH** verbs because doesn't exists a `case "PATCH"` clause when the route function is generated in `conf/app/app.go`, which throws a 404 Not Found error when trying to request data to any endpoint with **PATCH**.

Please check if it's a bug with mercurius-swagger-codegen or something like that.

Regards.

**Comment by felipeweb** [comment]
It is not a bug here is on https://github.com/novatrixtech/swagger-codegen

**Comment by felipeweb** [comment]
fix here https://github.com/novatrixtech/swagger-codegen/commit/98004c9bdffcf15e3ed10cbeca0293b00c0eb6a6
