### ISSUE TITLE
Change type of enclosing brackets of bind params on app.go

### ISSUE THREAD

**Issue by bruferrari** [novatrixtech/mercurius#26]
In `app.go` when the file is generated by the code gen the params comes enclosed in a brackets like these ones => `{ }` and the macaron API doesn't support it, as an enhancement I'll suggest an implementation of a parser change the `{myObjId}` to `:myObjId` removing the mentioned brackets and adding just the `:` sign, for example.

**Comment by felipeweb** [comment]
@bruferrari this is a codegen issue could open on codegen repo?
