### ISSUE TITLE
make terminal UI more friendly and more readable

### ISSUE THREAD

**Issue by felipeweb** [novatrixtech/mercurius#3]
We can use https://github.com/fatih/color for this

![image](https://cloud.githubusercontent.com/assets/4874009/19747223/28785ee6-9bb9-11e6-9eb3-cffc3ef99b6b.png)

**Comment by Horaddrim** [comment]
I will take a look! :smile:

**Comment by felipeweb** [comment]
go ahead @Horaddrim 🎉 🎉

**Comment by jcbombardelli** [comment]
Can this issue still be resolved?

**Comment by felipeweb** [comment]
I think so

**Comment by jeffprestes** [comment]
Go ahead @jcbombardelli , you will be more than welcomed.

**Comment by jeffprestes** [comment]
This feature was implemented by @jcbombardelli
