### ISSUE TITLE
Mercurius needs to support CSRF and XSS attack preventions

### ISSUE THREAD

**Issue by bruferrari** [novatrixtech/mercurius#34]
- CSRF is already supported by macaron, so it's just configuration.
- XSS doesn't come out-of-the-box on macaron, maybe a good library could do this work for us.

**Comment by felipeweb** [comment]
@bruferrari  we can use this for xss https://github.com/unrolled/secure and this csrf https://github.com/go-macaron/csrf

**Comment by bruferrari** [comment]
Looks good for me @felipeweb, if you want to work on it I'm already working on macaron CSRF implementation 😄

**Comment by felipeweb** [comment]
nice, maybe i will work on xss tomorrow night @bruferrari

**Comment by jeffprestes** [comment]
Any news on this guys?

**Comment by jeffprestes** [comment]
Any news?

**Comment by jeffprestes** [comment]
Just use Macaron Plug In: https://github.com/go-macaron/csrf
