### ISSUE TITLE
Add native support to HTTPS

### ISSUE THREAD

**Issue by jeffprestes** [novatrixtech/mercurius#41]
Add support to start application with HTTPS.
Please consider to use the code below:
```
port := port()
if port == 443 {
	app.Run("0.0.0.0", port, getFullchainPemFilePath(), getPrivatekeyPemFilePath())
	return
}
app.Run(port)
// configure http port
func port() int {
	port, err := config.Cfg.Section("").Key("http_port").Int()
	if err != nil {
		log.Fatal(err)
	}

	if forceLocal, _ := config.Cfg.Section("").Key("force_local_http_port").Bool(); forceLocal == false {
		if i, err := strconv.Atoi(os.Getenv("PORT")); err == nil {
			port = i
		}
	}
	return port
}

func getFullchainPemFilePath() string {
	fullchain := config.Cfg.Section("").Key("fullchain_path").String()
	return fullchain
}

func getPrivatekeyPemFilePath() string {
	privatekey := config.Cfg.Section("").Key("privatekey_path").String()
	return privatekey
}
```

**Comment by jeffprestes** [comment]
Add these keys into standard app.ini
```
fullchain_path = 
privatekey_path =  
```

**Comment by mikey2020** [comment]
hi @jeffprestes 
Am interested in this issue

**Comment by jeffprestes** [comment]
So, please, go ahead

**Comment by mikey2020** [comment]
hi @jeffprestes 
I have a couple of questions about this issue, is there a platform where I can ask questions about the project?

**Comment by jeffprestes** [comment]
You can ask here. No problem.

Em seg, 26 de nov de 2018 13:14, mikey2020 <notifications@github.com
escreveu:

**Comment by mikey2020** [comment]
Questions
1. Is this feature meant to be implemented by default or only by the user's choice 
2.  Are these keys meant to have default values
```
fullchain_path = 
privatekey_path =  
```

**Comment by jeffprestes** [comment]
1A. I think it would be more appropriate under user's consent.

2A. If user wants to, it would be great if the Mercurius setup generates
the keys automatically and set these parameters



Em seg, 26 de nov de 2018 17:01, mikey2020 <notifications@github.com
escreveu:

**Comment by mikey2020** [comment]
Hi @jeffprestes 
About this code `Run("0.0.0.0", port, getFullchainPemFilePath(), getPrivatekeyPemFilePath())`
I checked macaron `Run` function and it does not use the http.ListenAndServeTLS function so it wont support the use of TLS
```
func (m *Macaron) Run(args ...interface{}) {
	host, port := GetDefaultListenInfo()
	if len(args) == 1 {
		switch arg := args[0].(type) {
		case string:
			host = arg
		case int:
			port = arg
		}
	} else if len(args) >= 2 {
		if arg, ok := args[0].(string); ok {
			host = arg
		}
		if arg, ok := args[1].(int); ok {
			port = arg
		}
	}

	addr := host + ":" + com.ToStr(port)
	logger := m.Injector.GetVal(reflect.TypeOf(m.logger)).Interface().(*log.Logger)
	logger.Printf("listening on %s (%s)\n", addr, Env)
	logger.Fatalln(http.ListenAndServe(addr, m))
}
```

**Comment by jeffprestes** [comment]
Yeah... I have been thinking to perform Macaron's fork and implement this
feature and use it at Mercurius.
In each Macaron's new version we update the fork and update the Mercurius
but keeping this feature.
What do you think?

-Jeff Prestes

**Comment by mikey2020** [comment]
I think that would be great

**Comment by mikey2020** [comment]
Would this issue be placed on hold while the macaron feature is being implemented

**Comment by jeffprestes** [comment]
Closing this as the model to implement this feature was described at: https://github.com/novatrixtech/mercurius/issues/37
