### ISSUE TITLE
Conexão com Postgres com Erro

### ISSUE THREAD

**Issue by jeffersonsc** [novatrixtech/mercurius#42]
Olá,

No meu projeto eu seto o parametro db_type como postgres porem ele apresentou alguns errors:

Primeiro: não concetava com o banco por erro de drive por que postgresql não existia ai troquei o db_type para postgres.
Segundo: após ação de cima deu outro erro não tinha a string de conexão quando fui olhar a comparação estava com argumento "postgresql" alterei para "postgres" e funcionou
Terceiro: agora não dava erro de drive mas sim de SLL por que esse modo está ativado na query padrão, para esse erro tive que alterar a linha.

```
DE: return fmt.Sprintf("postgres://%s:%s@%s:%s/%s?", DBConnData.User, DBConnData.Pw, DBConnData.Host, DBConnData.Port, DBConnData.DBName)

Note o argumento "sslmode" como disable
PARA: return fmt.Sprintf("user=%s password=%s host=%s port=%s dbname=%s sslmode=disable", DBConnData.User, DBConnData.Pw, DBConnData.Host, DBConnData.Port, DBConnData.DBName)

```

Espero ter ajudado e que essa correção para o banco postgres venha na próxima versão.

**Comment by jeffprestes** [comment]
Oi Jefferson,

primeiro, muito obrigado pela contribuição. 
Uma pergunta, na sua string de conexão não tem mais o "postgres://"?

**Comment by jeffprestes** [comment]
Fiz os ajustes no branch postgres-mongo, pode testar?

**Comment by jeffprestes** [comment]
Ajustado com o ultimo PR. #44
